on:
  push:
    branches:
    - main
env:
  AZURE_FUNCTIONAPP_NAME: xuaps-st-functionapp-poduction-we
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './functions/src'
  PYTHON_VERSION: '3.9'
  APP_PATH: ./app
  FUNCTIONS_PATH: ./functions
 
jobs:
  lint:
    name: 'Lint App'
    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    # Checkout the repository to the GitHub Actions runner
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.2'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install dependencies
      working-directory: ${{ env.APP_PATH }} 
      run: npm ci --ignore-scripts

    - name: Linter
      working-directory: ${{ env.APP_PATH }} 
      run: npm run lint

  test:
    name: 'Test App'
    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    # Checkout the repository to the GitHub Actions runner
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.2'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install dependencies
      working-directory: ${{ env.APP_PATH }} 
      run: npm ci --ignore-scripts

    - name: Tests
      working-directory: ${{ env.APP_PATH }} 
      run: npm run test

  cypress:
      name: 'E2E App'
      runs-on: ubuntu-latest
      environment: production
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
        - name: Cypress run
          uses: cypress-io/github-action@v2
          with:
            working-directory: ${{ env.APP_PATH }} 
            build: npm run build
            start: npm start

        - uses: actions/upload-artifact@v2
          if: failure()
          with:
            name: cypress-screenshots
            path: app/cypress/screenshots

  build-and-deploy:
    needs: [lint, test, cypress]
    concurrency: ci-${{ github.ref }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        working-directory: ${{ env.APP_PATH }} 
        run: |
          npm ci --ignore-scripts
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages 
          folder: app/dist 

